<h1 align="center"> Movie Recommended System </h1>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
holl_mov = pd.read_csv("/content/tmdb_5000_movies.csv")
holl_cred = pd.read_csv("/content/tmdb_5000_credits.csv")
# indian_mov = pd.read_csv("indian movies.csv")
# boll_mov = pd.read_csv("BollywoodMovieDetail.csv")

In [ ]:
print(holl_mov.shape)
holl_mov.head(10)

(4803, 20)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004

In [ ]:
print(holl_cred.shape)
holl_cred.head(10)

(4803, 4)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
5,559,Spider-Man 3,"[{""cast_id"": 30, ""character"": ""Peter Parker / ...","[{""credit_id"": ""52fe4252c3a36847f80151a5"", ""de..."
6,38757,Tangled,"[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."
7,99861,Avengers: Age of Ultron,"[{""cast_id"": 76, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""55d5f7d4c3a3683e7e0016eb"", ""de..."
8,767,Harry Potter and the Half-Blood Prince,"[{""cast_id"": 3, ""character"": ""Harry Potter"", ""...","[{""credit_id"": ""52fe4273c3a36847f801fab1"", ""de..."
9,209112,Batman v Superman: Dawn of Justice,"[{""cast_id"": 18, ""character"": ""Bruce Wayne / B...","[{""credit_id"": ""553bf23692514135c8002886"", ""de..."

In [ ]:
# print(indian_mov.shape)
# indian_mov.rename(columns={'Movie Name':'title'},inplace=True)
# indian_mov.head(10)

In [ ]:
# print(boll_mov.shape)
# boll_mov.head(10)

In [ ]:
movies = holl_mov.merge(holl_cred,on="title")

In [ ]:
movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [ ]:
# indian_mov.merge(boll_mov,on="title")

In [ ]:
movies = movies[['movie_id','title','genres','cast','overview','keywords','crew']]

In [ ]:
movies.head(3)

,movie_id,title,genres,cast,overview,keywords,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [ ]:
movies.dropna(inplace=True)

In [ ]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
import ast
def convert(obj):
    li = []
    for i in ast.literal_eval(obj):
        li.append(i['name'])
    return li

In [ ]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [ ]:
movies['genres'] = movies['genres'].apply(convert)

In [ ]:
movies

,movie_id,title,genres,cast,overview,keywords,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...",El Mariachi just wants to play his guitar and ...,"[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,"[Comedy, Romance]","[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...",A newlywed couple's honeymoon is upended by th...,[],"[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...",When ambitious New York attorney Sam is sent t...,[],"[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,[Documentary],"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...",Ever since the second grade when he first saw ...,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [ ]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head(3)

,movie_id,title,genres,cast,overview,keywords,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",A cryptic message from Bondâ€™s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [ ]:
def convert3(obj):
    li = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            li.append(i['name'])
            counter += 1
        else:
            break
    return li

In [ ]:
movies['cast'] = movies['cast'].apply(convert3)
movies.head(3)

,movie_id,title,genres,cast,overview,keywords,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",A cryptic message from Bondâ€™s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [ ]:
def fd(obj):
    li = []
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            li.append(i['name'])
            break
    return li

In [ ]:
movies['crew'] = movies['crew'].apply(fd)
movies.head(3)

,movie_id,title,genres,cast,overview,keywords,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",A cryptic message from Bondâ€™s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...",[Sam Mendes]

In [ ]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [ ]:
movies.head(3)

,movie_id,title,genres,cast,overview,keywords,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[A, cryptic, message, from, Bondâ€™s, past, send...","[spy, based on novel, secret agent, sequel, mi...",[Sam Mendes]

In [ ]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [ ]:
movies.head()

,movie_id,title,genres,cast,overview,keywords,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...",[GoreVerbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]","[A, cryptic, message, from, Bondâ€™s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...",[SamMendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...",[ChristopherNolan]
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...",[AndrewStanton]

In [ ]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']
movies.head()

,movie_id,title,genres,cast,overview,keywords,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]","[A, cryptic, message, from, Bondâ€™s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
new_df = movies[['movie_id','title','tags']]

In [ ]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
new_df.head(3)

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...

In [ ]:
new_df['tags'][1]

"Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. Adventure Fantasy Action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger JohnnyDepp OrlandoBloom KeiraKnightley GoreVerbinski"

In [ ]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [ ]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski"

In [ ]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [ ]:
ps.stem('Loved')

'love'

In [ ]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [ ]:
new_df['tags'] = new_df['tags'].apply(stem)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
vectors.shape

(4806, 5000)

In [ ]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
cv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloÃ«gracemoretz',
 'chloÃ«sevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciarÃ¡nhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(vectors)

In [ ]:
print(similarity.shape)
similarity[0]

(4806, 4806)

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [ ]:
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].title)

In [ ]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [ ]:
recommend('Superman')

Superman Returns
Superman II
Iron Man 2
Superman III
Superman IV: The Quest for Peace

In [ ]:
import pickle

In [ ]:
pickle.dump(new_df,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [ ]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [ ]:
movie_list_pr = list(new_df['title'].values)

In [ ]:
movie_list_pr

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',
 'TRON: Legacy',
 'Cars 2',
 'Green Lantern',
 'Toy Story 3',
 'Terminator Salvation',
 'Furious 7',
 'World War Z',
 'X-Men: Days of Future Past',
 'Star Trek Into Darkness',
 'Jack the Giant Slayer',
 'The Great Gatsby',
 'Prince of Persia: The Sands of Time',
 'Pacific Rim',
 'Transformers: Dark of the Moon',
 'Indiana Jones and the Kingdom of the Crystal Skull',
 'The Good Dinosaur',
 'Brave',
 'Star Trek Beyond',
 'WALLÂ·E',
 'Rush Hour 3',
 '2012',
 'A Christmas Carol',
 'Jupiter Ascending',
 'The Legend of Tarzan',
 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
 'X-Men: Apocalypse',
 'The Dark Knight',
 'Up',
 'Monsters vs Aliens',
 'Iron Man',
 'Hugo',
 'Wild Wild West',
 'The Mummy: Tomb of the Dragon Emperor',
 'Suicide Squad',
 'Evan Almighty',
 'Edge of Tomorrow',
 'Waterworld',
 'G.I. Joe: The Rise of Cobra',
 'Inside Out',
 'The Jungle Book',
 'Iron Man 2',
 'Snow White and the Huntsman',
 'Maleficent',
 'Dawn of the Planet of the Apes',
 'The Lovers',
 '47 Ronin',
 'Captain America: The Winter Soldier',
 'Shrek Forever After',
 'Tomorrowland',
 'Big Hero 6',
 'Wreck-It Ralph',
 'The Polar Express',
 'Independence Day: Resurgence',
 'How to Train Your Dragon',
 'Terminator 3: Rise of the Machines',
 'Guardians of the Galaxy',
 'Interstellar',
 'Inception',
 'Shin Godzilla',
 'The Hobbit: An Unexpected Journey',
 'The Fast and the Furious',
 'The Curious Case of Benjamin Button',
 'X-Men: First Class',
 'The Hunger Games: Mockingjay - Part 2',
 "The Sorcerer's Apprentice",
 'Poseidon',
 'Alice Through the Looking Glass',
 'Shrek the Third',
 'Warcraft',
 'Terminator Genisys',
 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
 'Pearl Harbor',
 'Transformers',
 'Alexander',
 'Harry Potter and the Order of the Phoenix',
 'Harry Potter and the Goblet of Fire',
 'Hancock',
 'I Am Legend',
 'Charlie and the Chocolate Factory',
 'Ratatouille',
 'Batman Begins',
 'Madagascar: Escape 2 Africa',
 'Night at the Museum: Battle of the Smithsonian',
 'X-Men Origins: Wolverine',
 'The Matrix Revolutions',
 'Frozen',
 'The Matrix Reloaded',
 'Thor: The Dark World',
 'Mad Max: Fury Road',
 'Angels & Demons',
 'Thor',
 'Bolt',
 'G-Force',
 'Wrath of the Titans',
 'Dark Shadows',
 'Mission: Impossible - Rogue Nation',
 'The Wolfman',
 'Bee Movie',
 'Kung Fu Panda 2',
 'The Last Airbender',
 'Mission: Impossible III',
 'White House Down',
 'Mars Needs Moms',
 'Flushed Away',
 'Pan',
 'Mr. Peabody & Sherman',
 'Troy',
 "Madagascar 3: Europe's Most Wanted",
 'Die Another Day',
 'Ghostbusters',
 'Armageddon',
 'Men in Black II',
 'Beowulf',
 'Kung Fu Panda 3',
 'Mission: Impossible - Ghost Protocol',
 'Rise of the Guardians',
 'Fun with Dick and Jane',
 'The Last Samurai',
 'Exodus: Gods and Kings',
 'Star Trek',
 'Spider-Man',
 'How to Train Your Dragon 2',
 'Gods of Egypt',
 'Stealth',
 'Watchmen',
 'Lethal Weapon 4',
 'Hulk',
 'G.I. Joe: Retaliation',
 'Sahara',
 'Final Fantasy: The Spirits Within',
 'Captain America: The First Avenger',
 'The World Is Not Enough',
 'Master and Commander: The Far Side of the World',
 'The Twilight Saga: Breaking Dawn - Part 2',
 'Happy Feet Two',
 'The Incredible Hulk',
 'The BFG',
 'The Revenant',
 'Turbo',
 'Rango',
 'Penguins of Madagascar',
 'The Bourne Ultimatum',
 'Kung Fu Panda',
 'Ant-Man',
 'The Hunger Games: Catching Fire',
 'Home',
 'War of the Worlds',
 'Bad Boys II',
 'Puss in Boots',
 'Salt',
 'Noah',
 'The Adventures of Tintin',
 'Harry Potter and the Prisoner of Azkaban',
 'Australia',
 'After Earth',
 'Dinosaur',
 'Night at the Museum: Secret of the Tomb',
 'Megamind',
 "Harry Potter and the Philosopher's Stone",
 'R.I.P.D.',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'The Hunger Games: Mockingjay - Part 1',
 'The Da Vinci Code',
 'Rio 2',
 'X2',
 'Fast Five',
 'Sherlock Holmes: A Game of Shadows',
 'Clash of the Titans',
 'Total Recall',
 'The 13th Warrior',
 'The Bourne Legacy',
 'Batman & Robin',
 'How the Grinch Stole Christmas',
 'The Day After Tomorrow',
 'Mission: Impossible II',
 'The Perfect Storm',
 'Fantastic 4: Rise of the Silver Surfer',
 'Life of Pi',
 'Ghost Rider',
 'Jason Bourne',
 "Charlie's Angels: Full Throttle",
 'Prometheus',
 'Stuart Little 2',
 'Elysium',
 'The Chronicles of Riddick',
 'RoboCop',
 'Speed Racer',
 'How Do You Know',
 'Knight and Day',
 'Oblivion',
 'Star Wars: Episode III - Revenge of the Sith',
 'Star Wars: Episode II - Attack of the Clones',
 'Monsters, Inc.',
 'The Wolverine',
 'Star Wars: Episode I - The Phantom Menace',
 'The Croods',
 'Asterix at the Olympic Games',
 'Windtalkers',
 "The Huntsman: Winter's War",
 'Teenage Mutant Ninja Turtles',
 'Gravity',
 "Dante's Peak",
 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 'Fantastic Four',
 'Night at the Museum',
 'San Andreas',
 'Tomorrow Never Dies',
 'The Patriot',
 "Ocean's Twelve",
 'Mr. & Mrs. Smith',
 'Insurgent',
 'The Aviator',
 "Gulliver's Travels",
 'The Green Hornet',
 '300: Rise of an Empire',
 'The Smurfs',
 'Home on the Range',
 'Allegiant',
 'Real Steel',
 'The Smurfs 2',
 'Speed 2: Cruise Control',
 "Ender's Game",
 'Live Free or Die Hard',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Around the World in 80 Days',
 'Ali',
 'The Cat in the Hat',
 'I, Robot',
 'Kingdom of Heaven',
 'Stuart Little',
 'The Princess and the Frog',
 'The Martian',
 'The Island',
 'Town & Country',
 'Gone in Sixty Seconds',
 'Gladiator',
 'Minority Report',
 'Harry Potter and the Chamber of Secrets',
 'Casino Royale',
 'Planet of the Apes',
 'Terminator 2: Judgment Day',
 'Public Enemies',
 'American Gangster',
 'True Lies',
 'The Taking of Pelham 1 2 3',
 'Little Fockers',
 'The Other Guys',
 'Eraser',
 'Django Unchained',
 'The Hunchback of Notre Dame',
 "The Emperor's New Groove",
 'The Expendables 2',
 'National Treasure',
 'Eragon',
 'Where the Wild Things Are',
 'Epic',
 'The Tourist',
 'End of Days',
 'Blood Diamond',
 'The Wolf of Wall Street',
 'Batman Forever',
 'Starship Troopers',
 'Cloud Atlas',
 "Legend of the Guardians: The Owls of Ga'Hoole",
 'Catwoman',
 'Hercules',
 'Treasure Planet',
 'Land of the Lost',
 'The Expendables 3',
 'Point Break',
 'Son of the Mask',
 'In the Heart of the Sea',
 'The Adventures of Pluto Nash',
 'Green Zone',
 'The Peanuts Movie',
 'The Spanish Prisoner',
 'The Mummy Returns',
 'Gangs of New York',
 'The Flowers of War',
 "Surf's Up",
 'The Stepford Wives',
 'Black Hawk Down',
 'The Campaign',
 'The Fifth Element',
 'Sex and the City 2',
 'The Road to El Dorado',
 'Ice Age: Continental Drift',
 'Cinderella',
 'The Lovely Bones',
 'Finding Nemo',
 'The Lord of the Rings: The Return of the King',
 'The Lord of the Rings: The Two Towers',
 'Seventh Son',
 'Lara Croft: Tomb Raider',
 'Transcendence',
 'Jurassic Park III',
 'Rise of the Planet of the Apes',
 'The Spiderwick Chronicles',
 'A Good Day to Die Hard',
 'The Alamo',
 'The Incredibles',
 'Cutthroat Island',
 'Percy Jackson & the Olympians: The Lightning Thief',
 'Men in Black',
 'Toy Story 2',
 'Unstoppable',
 'Rush Hour 2',
 'What Lies Beneath',
 'Cloudy with a Chance of Meatballs',
 'Ice Age: Dawn of the Dinosaurs',
 'The Secret Life of Walter Mitty',
 "Charlie's Angels",
 'The Departed',
 'Mulan',
 'Tropic Thunder',
 'The Girl with the Dragon Tattoo',
 'Die Hard: With a Vengeance',
 'Sherlock Holmes',
 'Ben-Hur',
 'Atlantis: The Lost Empire',
 'Alvin and the Chipmunks: The Road Chip',
 'Valkyrie',
 "You Don't Mess with the Zohan",
 'Pixels',
 'A.I. Artificial Intelligence',
 'The Haunted Mansion',
 'Contact',
 'Hollow Man',
 'The Interpreter',
 'Percy Jackson: Sea of Monsters',
 'Lara Croft Tomb Raider: The Cradle of Life',
 'Now You See Me 2',
 'The Saint',
 'Spy Game',
 'Mission to Mars',
 'Rio',
 'Bicentennial Man',
 'Volcano',
 "The Devil's Own",
 'K-19: The Widowmaker',
 'Conan the Barbarian',
 'Cinderella Man',
 'The Nutcracker: The Untold Story',
 'Seabiscuit',
 'Twister',
 'Cast Away',
 'Happy Feet',
 'The Bourne Supremacy',
 'Air Force One',
 "Ocean's Eleven",
 'The Three Musketeers',
 'Hotel Transylvania',
 'Enchanted',
 'Safe House',
 '102 Dalmatians',
 'Tower Heist',
 'The Holiday',
 'Enemy of the State',
 "It's Complicated",
 "Ocean's Thirteen",
 'Open Season',
 'Divergent',
 'Enemy at the Gates',
 'The Rundown',
 'Last Action Hero',
 'Memoirs of a Geisha',
 'The Fast and the Furious: Tokyo Drift',
 'Arthur Christmas',
 'Meet Joe Black',
 'Collateral Damage',
 'All That Jazz',
 'Mirror Mirror',
 'Scott Pilgrim vs. the World',
 'The Core',
 'Nutty Professor II: The Klumps',
 'Scooby-Doo',
 'Dredd',
 'Click',
 'Creepshow',
 'Cats & Dogs 2 : The Revenge of Kitty Galore',
 'Jumper',
 'Hellboy II: The Golden Army',
 'Zodiac',
 'The 6th Day',
 'Bruce Almighty',
 'The Expendables',
 'Mission: Impossible',
 'The Hunger Games',
 'The Hangover Part II',
 'Batman Returns',
 'Over the Hedge',
 'Lilo & Stitch',
 "Charlotte's Web",
 'Deep Impact',
 'RED 2',
 'The Longest Yard',
 'Alvin and the Chipmunks: Chipwrecked',
 'Grown Ups 2',
 'Get Smart',
 "Something's Gotta Give",
 'Shutter Island',
 'Four Christmases',
 'Robots',
 'Face/Off',
 'Bedtime Stories',
 'Road to Perdition',
 'Just Go with It',
 'Con Air',
 'Eagle Eye',
 'Cold Mountain',
 'The Book of Eli',
 'Flubber',
 'The Haunting',
 'Space Jam',
 'The Pink Panther',
 'The Day the Earth Stood Still',
 'Conspiracy Theory',
 'Fury',
 'Six Days Seven Nights',
 'Yogi Bear',
 'Spirit: Stallion of the Cimarron',
 'Zookeeper',
 'Lost in Space',
 'The Manchurian Candidate',
 'DÃ©jÃ  Vu',
 'Hotel Transylvania 2',
 'Fantasia 2000',
 'The Time Machine',
 'Mighty Joe Young',
 'Swordfish',
 'The Legend of Zorro',
 'What Dreams May Come',
 'Little Nicky',
 'The Brothers Grimm',
 'Mars Attacks!',
 'Evolution',
 'The Edge',
 'Surrogates',
 'Thirteen Days',
 'Daylight',
 'Walking With Dinosaurs',
 'Battlefield Earth',
 'Looney Tunes: Back in Action',
 'Nine',
 'Timeline',
 'The Postman',
 'Babe: Pig in the City',
 'The Last Witch Hunter',
 'Red Planet',
 'Arthur and the Invisibles',
 'Oceans',
 'A Sound of Thunder',
 'Pompeii',
 'Top Cat Begins',
 'A Beautiful Mind',
 'The Lion King',
 'Journey 2: The Mysterious Island',
 'Cloudy with a Chance of Meatballs 2',
 'Red Dragon',
 'Hidalgo',
 'Jack and Jill',
 '2 Fast 2 Furious',
 'The Little Prince',
 'The Invasion',
 'The Adventures of Rocky & Bullwinkle',
 'The Secret Life of Pets',
 'The League of Extraordinary Gentlemen',
 'Despicable Me 2',
 'Independence Day',
 'The Lost World: Jurassic Park',
 'Madagascar',
 'Children of Men',
 'X-Men',
 'Wanted',
 'The Rock',
 'Ice Age: The Meltdown',
 '50 First Dates',
 'Hairspray',
 'Exorcist: The Beginning',
 'Inspector Gadget',
 'Now You See Me',
 'Grown Ups',
 'The Terminal',
 'Hotel for Dogs',
 'Vertical Limit',
 "Charlie Wilson's War",
 'Shark Tale',
 'Dreamgirls',
 'Be Cool',
 'Munich',
 'Tears of the Sun',
 'Killers',
 'The Man from U.N.C.L.E.',
 'Spanglish',
 'Monster House',
 'Bandits',
 'First Knight',
 'Anna and the King',
 'Immortals',
 'Hostage',
 'Titan A.E.',
 'Hollywood Homicide',
 'Soldier',
 'Carriers',
 'Monkeybone',
 'Flight of the Phoenix',
 'Unbreakable',
 'Minions',
 'Sucker Punch',
 'Snake Eyes',
 'Sphere',
 'The Angry Birds Movie',
 "Fool's Gold",
 'Funny People',
 'The Kingdom',
 'Talladega Nights: The Ballad of Ricky Bobby',
 'Dr. Dolittle 2',
 'Braveheart',
 'Jarhead',
 'The Simpsons Movie',
 'The Majestic',
 'Driven',
 'Two Brothers',
 'The Village',
 'Doctor Dolittle',
 'Signs',
 'Shrek 2',
 'Cars',
 'Runaway Bride',
 'xXx',
 'The SpongeBob Movie: Sponge Out of Water',
 'Ransom',
 'Inglourious Basterds',
 'Hook',
 'Die Hard 2',
 'S.W.A.T.',
 'Vanilla Sky',
 'Lady in the Water',
 'AVP: Alien vs. Predator',
 'Alvin and the Chipmunks: The Squeakquel',
 'We Were Soldiers',
 'Olympus Has Fallen',
 'Star Trek: Insurrection',
 'Battle: Los Angeles',
 'Big Fish',
 'Wolf',
 'War Horse',
 'The Monuments Men',
 'The Abyss',
 'Wall Street: Money Never Sleeps',
 'Dracula Untold',
 'The Siege',
 'Stardust',
 'Seven Years in Tibet',
 'The Dilemma',
 'Bad Company',
 'Doom',
 'I Spy',
 'Underworld: Awakening',
 'Rock of Ages',
 "Hart's War",
 'Killer Elite',
 'Rollerball',
 'Ballistic: Ecks vs. Sever',
 'Hard Rain',
 'Osmosis Jones',
 "Legends of Oz: Dorothy's Return",
 'Blackhat',
 'Sky Captain and the World of Tomorrow',
 'Basic Instinct 2',
 'Escape Plan',
 'The Legend of Hercules',
 'The Sum of All Fears',
 'The Twilight Saga: Eclipse',
 'The Score',
 'Despicable Me',
 'Money Train',
 'Ted 2',
 'Agora',
 'Mystery Men',
 'Hall Pass',
 'The Insider',
 'The Finest Hours',
 'Body of Lies',
 'Dinner for Schmucks',
 'Abraham Lincoln: Vampire Hunter',
 'Entrapment',
 'The X Files',
 'The Last Legion',
 'Saving Private Ryan',
 'Need for Speed',
 'What Women Want',
 'Ice Age',
 'Dreamcatcher',
 'Lincoln',
 'The Matrix',
 'Apollo 13',
 'The Santa Clause 2',
 'Les MisÃ©rables',
 "You've Got Mail",
 'Step Brothers',
 'The Mask of Zorro',
 'Due Date',
 'Unbroken',
 'Space Cowboys',
 'Cliffhanger',
 'Broken Arrow',
 'The Kid',
 'World Trade Center',
 'Mona Lisa Smile',
 'The Dictator',
 'Eyes Wide Shut',
 'Annie',
 'Focus',
 'This Means War',
 'Blade: Trinity',
 'Red Dawn',
 'Primary Colors',
 'Resident Evil: Retribution',
 'Death Race',
 'The Long Kiss Goodnight',
 'Proof of Life',
 'Zathura: A Space Adventure',
 'Fight Club',
 'We Are Marshall',
 'Hudson Hawk',
 'Lucky Numbers',
 'I, Frankenstein',
 'Oliver Twist',
 'Elektra',
 'Sin City: A Dame to Kill For',
 'Random Hearts',
 'Everest',
 'Perfume: The Story of a Murderer',
 'Austin Powers in Goldmember',
 'Astro Boy',
 'Jurassic Park',
 'Wyatt Earp',
 'Clear and Present Danger',
 'Dragon Blade',
 'Little Man',
 'U-571',
 'The American President',
 'The Love Guru',
 '3000 Miles to Graceland',
 'The Hateful Eight',
 'Blades of Glory',
 'Hop',
 '300',
 'Meet the Fockers',
 'Marley & Me',
 'The Green Mile',
 'Wild Hogs',
 'Chicken Little',
 'Gone Girl',
 'The Bourne Identity',
 'GoldenEye',
 "The General's Daughter",
 'The Truman Show',
 'The Prince of Egypt',
 'Daddy Day Care',
 '2 Guns',
 'Cats & Dogs',
 'The Italian Job',
 'Two Weeks Notice',
 'Antz',
 'Couples Retreat',
 'Days of Thunder',
 'Cheaper by the Dozen 2',
 'Maze Runner: The Scorch Trials',
 'Eat Pray Love',
 'The Family Man',
 'RED',
 'Any Given Sunday',
 'The Horse Whisperer',
 'Collateral',
 'The Scorpion King',
 'Ladder 49',
 'Jack Reacher',
 'Deep Blue Sea',
 'This Is It',
 'Contagion',
 'Kangaroo Jack',
 'Coraline',
 'The Happening',
 'Man on Fire',
 'The Shaggy Dog',
 'Starsky & Hutch',
 'Jingle All the Way',
 'Hellboy',
 'A Civil Action',
 'ParaNorman',
 'The Jackal',
 'Paycheck',
 'Up Close & Personal',
 'The Tale of Despereaux',
 'The Tuxedo',
 'Under Siege 2: Dark Territory',
 'Jack Ryan: Shadow Recruit',
 'Joy',
 'London Has Fallen',
 'Alien: Resurrection',
 'Shooter',
 'The Boxtrolls',
 'Practical Magic',
 'The Lego Movie',
 'Miss Congeniality 2: Armed and Fabulous',
 'Reign of Fire',
 'Gangster Squad',
 'Year One',
 'Invictus',
 'State of Play',
 'Duplicity',
 'My Favorite Martian',
 'The Sentinel',
 'Planet 51',
 'Star Trek: Nemesis',
 'Intolerable Cruelty',
 'Trouble with the Curve',
 'Edge of Darkness',
 'The Relic',
 'Analyze That',
 'Righteous Kill',
 'Mercury Rising',
 'The Soloist',
 'The Legend of Bagger Vance',
 'Almost Famous',
 'Garfield: A Tail of Two Kitties',
 'xXx: State of the Union',
 'Priest',
 'Sinbad: Legend of the Seven Seas',
 'Event Horizon',
 'Dragonfly',
 'The Black Dahlia',
 'Flyboys',
 'The Last Castle',
 'Supernova',
 "Winter's Tale",
 'The Mortal Instruments: City of Bones',
 'Meet Dave',
 'Dark Water',
 'Edtv',
 'Inkheart',
 'The Spirit',
 'Mortdecai',
 'In the Name of the King: A Dungeon Siege Tale',
 'Beyond Borders',
 'The Monkey King 2',
 'The Great Raid',
 'Deadpool',
 'Holy Man',
 'American Sniper',
 'Goosebumps',
 'Just Like Heaven',
 'The Flintstones in Viva Rock Vegas',
 'Rambo III',
 'Leatherheads',
 'The Ridiculous 6',
 'Did You Hear About the Morgans?',
 'The Internship',
 'Resident Evil: Afterlife',
 'Red Tails',
 "The Devil's Advocate",
 "That's My Boy",
 'DragonHeart',
 'After the Sunset',
 'Ghost Rider: Spirit of Vengeance',
 "Captain Corelli's Mandolin",
 'The Pacifier',
 'Walking Tall',
 'Forrest Gump',
 'Alvin and the Chipmunks',
 'Meet the Parents',
 'Pocahontas',
 'Superman',
 'The Nutty Professor',
 'Hitch',
 'George of the Jungle',
 'American Wedding',
 'Captain Phillips',
 'Date Night',
 'Casper',
 'The Equalizer',
 'Maid in Manhattan',
 'Crimson Tide',
 'The Pursuit of Happyness',
 'Flightplan',
 'Disclosure',
 'City of Angels',
 'Kill Bill: Vol. 1',
 'Bowfinger',
 'Kill Bill: Vol. 2',
 'Tango & Cash',
 'Death Becomes Her',
 'Shanghai Noon',
 'Executive Decision',
 "Mr. Popper's Penguins",
 'The Forbidden Kingdom',
 'Free Birds',
 'AlienÂ³',
 'Evita',
 'Ronin',
 'The Ghost and the Darkness',
 'Paddington',
 'The Watch',
 'The Hunted',
 'Instinct',
 'Stuck on You',
 'Semi-Pro',
 'The Pirates! In an Adventure with Scientists!',
 'Changeling',
 'Chain Reaction',
 'The Fan',
 'The Phantom of the Opera',
 'Elizabeth: The Golden Age',
 'Ã†on Flux',
 'Gods and Generals',
 'Turbulence',
 'Imagine That',
 'Muppets Most Wanted',
 'Thunderbirds',
 'Burlesque',
 'A Very Long Engagement',
 'Lolita',
 'D-Tox',
 'Blade II',
 'Seven Pounds',
 'Bullet to the Head',
 'The Godfather: Part III',
 'Elizabethtown',
 'You, Me and Dupree',
 'Superman II',
 'Gigli',
 "All the King's Men",
 'Shaft',
 'Anastasia',
 'Moulin Rouge!',
 'Domestic Disturbance',
 'Black Mass',
 'Flags of Our Fathers',
 'Law Abiding Citizen',
 'Grindhouse',
 'Beloved',
 'Lucky You',
 'Catch Me If You Can',
 'Zero Dark Thirty',
 'The Break-Up',
 'Mamma Mia!',
 "Valentine's Day",
 'The Dukes of Hazzard',
 'The Thin Red Line',
 'The Change-Up',
 'Man on the Moon',
 'Casino',
 'From Paris with Love',
 'Bulletproof Monk',
 'Me, Myself & Irene',
 'Barnyard',
 'Deck the Halls',
 'The Twilight Saga: New Moon',
 'Shrek',
 'The Adjustment Bureau',
 'Robin Hood: Prince of Thieves',
 'Jerry Maguire',
 'Ted',
 'As Good as It Gets',
 'Patch Adams',
 'Anchorman 2: The Legend Continues',
 'Mr. Deeds',
 'Super 8',
 'Erin Brockovich',
 'How to Lose a Guy in 10 Days',
 '22 Jump Street',
 'Interview with the Vampire',
 'Yes Man',
 'Central Intelligence',
 'Stepmom',
 "Daddy's Home",
 'Into the Woods',
 'Inside Man',
 'Payback',
 'Congo',
 'We Bought a Zoo',
 'Knowing',
 'Failure to Launch',
 'The Ring Two',
 'Crazy, Stupid, Love.',
 'Garfield',
 'Christmas with the Kranks',
 'Moneyball',
 'Outbreak',
 'Non-Stop',
 'Race to Witch Mountain',
 'V for Vendetta',
 'Shanghai Knights',
 'Curious George',
 'Herbie Fully Loaded',
 "Don't Say a Word",
 'Hansel & Gretel: Witch Hunters',
 'Unfaithful',
 'I Am Number Four',
 'Syriana',
 '13 Hours: The Secret Soldiers of Benghazi',
 'The Book of Life',
 'Firewall',
 'Absolute Power',
 'G.I. Jane',
 'The Game',
 'Silent Hill',
 'The Replacements',
 'American Reunion',
 'The Negotiator',
 'Into the Storm',
 'Beverly Hills Cop III',

In [1]:
import pickle

In [2]:
movie_list = pickle.load(open('C:\Users\Harshad\AI\Recommended Systemmovie_dict.pkl','rb'))

FileNotFoundError: [Errno 2] No such file or directory: 'movie_dict.pkl'